version: '3.9'

services:
  web:
    build: .
    image: slimerng-web:latest
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - SECURE_SSL_REDIRECT=0
      - SESSION_COOKIE_SECURE=0
      - CSRF_COOKIE_SECURE=0
      - CSRF_TRUSTED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
    volumes:
      - .:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    command: ["gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3", "--timeout", "60"]

volumes:
  static_data:
  media_data:


