# Generated by Django 5.2.4 on 2025-07-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slime_rng', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slimetype',
            options={'ordering': ['chance'], 'verbose_name': 'Тип слайма', 'verbose_name_plural': 'Типы слаймов'},
        ),
        migrations.AddField(
            model_name='craftrecipe',
            name='effect_type',
            field=models.CharField(blank=True, choices=[('harvestMultiplier', 'harvestMultiplier'), ('spinCooldown', 'spinCooldown'), ('rareChanceBoost', 'rareChanceBoost'), ('epicChanceBoost', 'epicChanceBoost'), ('divineChanceMultiplier', 'divineChanceMultiplier')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='craftrecipe',
            name='effect_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='craftrecipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='craft-items/'),
        ),
        migrations.AlterField(
            model_name='slimetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='slimes/'),
        ),
    ]
