# Generated by Django 5.2.4 on 2025-07-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slime_rng', '0002_alter_slimetype_options_craftrecipe_effect_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='effect_type',
            field=models.CharField(blank=True, choices=[('harvestMultiplier', 'harvestMultiplier'), ('spinCooldown', 'spinCooldown'), ('rareChanceBoost', 'rareChanceBoost'), ('epicChanceBoost', 'epicChanceBoost'), ('divineChanceMultiplier', 'divineChanceMultiplier')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='effect_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='collections/'),
        ),
    ]
