# Generated by Django 5.2.4 on 2025-07-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slime_rng', '0003_collection_claimed_collection_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='effect_type',
            field=models.CharField(blank=True, choices=[('harvestMultiplier', 'harvestMultiplier'), ('spinCooldown', 'spinCooldown'), ('rareChanceBoost', 'rareChanceBoost'), ('epicChanceBoost', 'epicChanceBoost'), ('mythicChanceBoost', 'mythicChanceBoost'), ('divineChanceMultiplier', 'divineChanceMultiplier')], max_length=50, null=True),
        ),
    ]
