# Generated by Django 5.2.4 on 2025-07-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slime_rng', '0004_alter_collection_effect_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
