# Generated by Django 5.0.7 on 2025-07-21 13:38

from django.db import migrations

def create_default_crafts(apps, schema_editor):
    SlimeType = apps.get_model('slime_rng', 'SlimeType')
    CraftRecipe = apps.get_model('slime_rng', 'CraftRecipe')
    CraftIngredient = apps.get_model('slime_rng', 'CraftIngredient')

    # Рецепт 1: Амулет удачи
    amulet_of_luck, created = CraftRecipe.objects.get_or_create(
        name="Амулет удачи",
        defaults={
            "effect": "Увеличивает шанс найти редкого слайма на 5%",
            "created_by_default": True,
            "effect_type": "rareChanceBoost",
            "effect_value": 0.05
        }
    )
    if created:
        try:
            green_slime = SlimeType.objects.get(name="Зелёный Слайм")
            blue_slime = SlimeType.objects.get(name="Синий Слайм")
            CraftIngredient.objects.create(recipe=amulet_of_luck, slime_type=green_slime, amount=10)
            CraftIngredient.objects.create(recipe=amulet_of_luck, slime_type=blue_slime, amount=5)
        except SlimeType.DoesNotExist:
            # Skip ingredient creation if slime types don't exist yet
            pass

    # Рецепт 2: Амулет скорости
    amulet_of_speed, created = CraftRecipe.objects.get_or_create(
        name="Амулет скорости",
        defaults={
            "effect": "Уменьшает время восстановления спина на 10%",
            "created_by_default": True,
            "effect_type": "spinCooldown",
            "effect_value": 0.9
        }
    )
    if created:
        try:
            red_slime = SlimeType.objects.get(name="Красный Слайм")
            yellow_slime = SlimeType.objects.get(name="Жёлтый Слайм")
            CraftIngredient.objects.create(recipe=amulet_of_speed, slime_type=red_slime, amount=10)
            CraftIngredient.objects.create(recipe=amulet_of_speed, slime_type=yellow_slime, amount=5)
        except SlimeType.DoesNotExist:
            # Skip ingredient creation if slime types don't exist yet
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('slime_rng', '0005_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.RunPython(create_default_crafts),
    ]
