# Generated by Django 5.2.4 on 2025-07-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slime_rng', '0006_populate_default_crafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercraft',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
