# Generated by Django 5.2.4 on 2025-07-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slime_rng', '0007_playercraft_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercraft',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
