# Generated by Django 5.2.4 on 2025-08-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slime_rng', '0008_playercraft_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercraft',
            name='created',
        ),
    ]
