# Generated by Django 5.2.4 on 2025-08-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slime_rng', '0009_remove_playercraft_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='epic_chance_boost',
            new_name='luck',
        ),
        migrations.RemoveField(
            model_name='user',
            name='divine_chance_multiplier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rare_chance_boost',
        ),
        migrations.AlterField(
            model_name='collection',
            name='effect_type',
            field=models.CharField(blank=True, choices=[('HarvestMultiplier', 'HarvestMultiplier'), ('SpinCooldown', 'SpinCooldown'), ('LuckBoost', 'LuckBoost')], default='LuckBoost', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='craftrecipe',
            name='effect_type',
            field=models.CharField(blank=True, choices=[('HarvestMultiplier', 'HarvestMultiplier'), ('SpinCooldown', 'SpinCooldown'), ('LuckBoost', 'LuckBoost')], default='LuckBoost', max_length=50, null=True),
        ),
    ]
