# Generated by Django 5.2.4 on 2025-08-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slime_rng', '0010_rename_epic_chance_boost_user_luck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='luck',
            field=models.FloatField(default=1.0),
        ),
    ]
